# Numpy

## Arrays e Primeiros Passos

In [1]:
# import numpy
import numpy as np

In [2]:
# posso iniciar com uma lista
lista = [1, 2, 3]
# podemos definir o tipo
np_array = np.array(lista, float)
# np_array = np.array([1,2,3], float)

In [3]:
np_array

array([1., 2., 3.])

In [4]:
type(np_array)

numpy.ndarray

In [5]:
vetor = np.array([1, 9, 8, 11, 12], float)

In [6]:
vetor[0]

1.0

In [7]:
# podemos suar tuplas

u = np.array((1, 2, 3, 4))
u

array([1, 2, 3, 4])

In [8]:
print(np_array)
print(type(np_array))

[1. 2. 3.]
<class 'numpy.ndarray'>


In [9]:
# alguns atributos
# verifica o tipo
type(np_array)

numpy.ndarray

In [10]:
# numero de dimensoes
# por ser um vetor, teremos como resultado 1 dimensão
# quando trabalhamos com matrizes teremos 2 dimensões
# a estrutura de um DataFrame terá 2 dimensões (linha, coluna)
np_array.ndim

1

In [11]:
np_array

array([1., 2., 3.])

In [12]:
# shape
np_array.shape

(3,)

In [13]:
# tamanho (numero de elementos)
np_array.size

3

In [14]:
# checa o dtype
np_array.dtype

dtype('float64')

Assim, como vimos os principais atributos do ndarray são:
* os tipos de dados (dtype) 
* shape
* size
* ndim


Atributo | Descrição
----------|------------
shape     | Tupla com o número de elementos de cada dimensão de vetor.
ndim      | Número de dimensões
nbytes    | Bytes usado para armazenar os dados em memória
dtype     | Dtype dos elementos contidos no vetor

In [15]:
# primeira matriz

In [16]:
dados = [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]
        ]

array = np.array(dados)
print(array)
print('Shape: ', array.shape)
print('Dimensões: ', array.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)
Dimensões:  2


**Essa matriz de dados parece com algo familiar?**

In [17]:
# Matriz transposta

In [18]:
matriz_inicial = np.array([[10, 20, 30],
                           [3, 50, 5],
                           [70, 80, 90],
                           [100, 110, 120]])

# Criando uma matriz Transposta
matriz_transposta = matriz_inicial.T
print('matriz inicial: ')
print(matriz_inicial)


print('matriz transposta: ')
print(matriz_transposta)

matriz inicial: 
[[ 10  20  30]
 [  3  50   5]
 [ 70  80  90]
 [100 110 120]]
matriz transposta: 
[[ 10   3  70 100]
 [ 20  50  80 110]
 [ 30   5  90 120]]


In [19]:
# arrays de 1 e 0
# zeros

z = np.zeros((2, 3))

# 
u = np.ones((3, 3), int)
i = np.identity(2, float)

In [20]:
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
np.zeros(shape = (4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
z.shape

(2, 3)

In [23]:
z.ndim

2

In [24]:
np.ones(shape = (10, 15))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
print(u)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [26]:
print(i)

[[1. 0.]
 [0. 1.]]


In [27]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Se quisermos um array com um valor específico, usamos o ```np.full```

In [28]:
np.full((2, 3), 0.7)

array([[0.7, 0.7, 0.7],
       [0.7, 0.7, 0.7]])

In [29]:
np.full(shape = (3, 3), fill_value = 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

* Outras funções para criar arrays

In [30]:
# np.arange
# similar a função nativa range(), mas diferente!
# no caso do range() nativo do Python não podemos usar número float como step
# retorna uma sequência de números

In [31]:
#list(range(1, 11, 2.5))
#TypeError: 'float' object cannot be interpreted as an integer

In [32]:
#np.arange(1, 101, 2)

In [33]:
#np.arange(1, 11, 0.1)

In [34]:
np.random.randint(1, 100, 10)

array([90, 39, 23, 27, 22, 39, 63, 32, 32, 77])

In [35]:
vetor1 = np.arange(1, 10, 1)
vetor1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
vetor2 = np.arange(1, 50, 0.5)
vetor2

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5, 22. , 22.5,
       23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5, 28. ,
       28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5, 33. , 33.5,
       34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. , 38.5, 39. ,
       39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5, 44. , 44.5,
       45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. , 49.5])

In [37]:
# np.linspace
# retorna número igualmente espaçados dentro de um intervalo numérico

In [38]:
vetor3 = np.linspace(1, 10, 5)
vetor3

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [39]:
# np.linspace(1, 50, 10)

Vejamos um sumário das principais funções para criar arrays com NumPy.

In [40]:
np.diag([0, 1, 2])

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [41]:
np.diag(np.arange(5, 51, 5))

array([[ 5,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 15,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 20,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 25,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 30,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 35,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 40,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 45,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 50]])

In [42]:
np.logspace(1, 100, 5, base = 2)

array([2.00000000e+00, 5.64316032e+07, 1.59226292e+15, 4.49269746e+22,
       1.26765060e+30])

``Sumário``

Function Name | Type of Array
--------------|--------------
np.array      | Create an array frm list, tuple, or iterable sequence, or another ndarray instance.
np.zeros      | Return a new array of given shape and type, filled with zeros.
np.ones       | Return a new array of given shape and type, filled with ones.
np.diag       | Creates a diagonal array with specified values along the diagonal and zeros elsewhere.
np.arange     | Return evenly spaced values within a given interval.
np.linspace   | Return evenly spaced numbers over a specified interval.
np.logspace   | Return numbers spaced evenly on a log scale.


## Manipulação das dimensões de um array

In [43]:
narray = np.full((2, 6), 1)

In [44]:
narray

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [45]:
# Transposta
narray.T.shape

(6, 2)

In [46]:
narray.shape

(2, 6)

In [47]:
n = narray.shape[0] # linhas
m = narray.shape[1] # colunas

In [48]:
produto = n * m
print(produto)

12


possibilidades:
- 3*4
- 6*2
- 4*3
- 1*12

In [49]:
narray.reshape(3, 4)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [50]:
narray.reshape(3, 4)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [51]:
narray.reshape(2, 6)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [52]:
narray.reshape(12, 1)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [53]:
narray.reshape(1, 12)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

O comando ravel distorce o array multidimensional e o transforma em um array 1D.

In [54]:
# ravel
narray = np.full((2, 6), 0.45)
narray

array([[0.45, 0.45, 0.45, 0.45, 0.45, 0.45],
       [0.45, 0.45, 0.45, 0.45, 0.45, 0.45]])

In [55]:
narray.ravel()

array([0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45,
       0.45])

## Fatiamento em arrays

In [56]:
lista = [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]

In [57]:
# monta a matriz
mat = np.array(lista)

In [58]:
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
# pega o elemento da linha 0 e índice da coluna 0
mat[0, 0]

0

In [60]:
# pega o elemento da linha 0 e índice da coluna 1
mat[0, 1]

1

In [61]:
# pega todos os elementos da linha 0
mat[0,:]

array([0, 1, 2, 3])

In [62]:
# pega todos os elementos da coluna 0
mat[:,0]

array([0, 4, 8])

In [63]:
# pega todos os elementos da coluna 2
mat[:,2]

array([ 2,  6, 10])